server.port=8080

spring.application.name=Airline-Reservation-System
spring.datasource.url=jdbc:mysql://localhost:3306/ars_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
